version: "3.8"

services:
  projekt-zaliczeniowy-www:
    image: 'projekt-zaliczeniowy-www:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always